import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="text-center">
          <h1 className={styles.title}>🌈 Rainbow</h1>
          <h2 className="text-2xl">Public APIs</h2>
          <div className="my-8 grid gap-4 grid-cols-2">
            <code><a href="/api/token-list">/token-list</a></code>
            <div>Get a list of ERC20 tokens</div>
          </div>
        </div>
      </main>
    </div>
  )
}
